// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDRV-GpLEPnpMZWLNq9WFGJcLVmWrGoUY',
    appId: '1:996671860466:web:01b6a1ac6d6ec60314aa6b',
    messagingSenderId: '996671860466',
    projectId: 'aapada-rakshak-cf6f6',
    authDomain: 'aapada-rakshak-cf6f6.firebaseapp.com',
    storageBucket: 'aapada-rakshak-cf6f6.firebasestorage.app',
    measurementId: 'G-1XTN0W4RCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVDK_J1Mj6g19wPinhib8hsS6fte0TSDs',
    appId: '1:996671860466:android:1f71b029caca83a214aa6b',
    messagingSenderId: '996671860466',
    projectId: 'aapada-rakshak-cf6f6',
    storageBucket: 'aapada-rakshak-cf6f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHkiBpknk0CCydvLOaTUP1s2n4MJU-CKs',
    appId: '1:996671860466:ios:36801a1aa702254014aa6b',
    messagingSenderId: '996671860466',
    projectId: 'aapada-rakshak-cf6f6',
    storageBucket: 'aapada-rakshak-cf6f6.firebasestorage.app',
    iosBundleId: 'com.example.aapdaRakshak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHkiBpknk0CCydvLOaTUP1s2n4MJU-CKs',
    appId: '1:996671860466:ios:36801a1aa702254014aa6b',
    messagingSenderId: '996671860466',
    projectId: 'aapada-rakshak-cf6f6',
    storageBucket: 'aapada-rakshak-cf6f6.firebasestorage.app',
    iosBundleId: 'com.example.aapdaRakshak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDRV-GpLEPnpMZWLNq9WFGJcLVmWrGoUY',
    appId: '1:996671860466:web:48acaa55cbbf047714aa6b',
    messagingSenderId: '996671860466',
    projectId: 'aapada-rakshak-cf6f6',
    authDomain: 'aapada-rakshak-cf6f6.firebaseapp.com',
    storageBucket: 'aapada-rakshak-cf6f6.firebasestorage.app',
    measurementId: 'G-DXQBRCLP72',
  );

}